import { lazy } from "react"
import {
  Grading,
  Sync,
  ViewModule,
  Notifications,
  Comment,
  TipsAndUpdates,
  Speed,
  Psychology,
  RateReview,
  SportsScore,
  Settings,
  Summarize,
  ManageAccounts,
  PsychologyAlt,
  Groups,
  AccountTree,
  AutoGraph,
  BatchPrediction,
  Timeline,
  Payments,
  Flag,
  Reviews,
} from "@mui/icons-material"
import { PAGE_URL } from "../resources/page_url.ts"

const AppraisalComponent = lazy(() => import("../components/pages/appraisal/appraisalComponent.tsx"))
const AppraisalFormComponent = lazy(() => import("../components/pages/appraisal/appraisalFormComponent.tsx"))
const PerformanceModulesComponent = lazy(() => import("../components/pages/performanceModulesComponent.tsx"))
const MyReviewComponent = lazy(() => import("../components/pages/myReview/myReviewComponent.tsx"))
const PeersViewComponent = lazy(() => import("../components/pages/teammates/peersViewComponent.tsx"))
const AppraiseeViewComponent = lazy(() => import("../components/pages/teammates/appraiseeViewComponent.tsx"))

export const performanceRoutes = [
  {
    title: "My Review",
    icon: Sync,
    path: PAGE_URL.myReview,
    element: <MyReviewComponent />,
    sideMenuView: true,
    children: [],
  },
  {
    title: "Teammates",
    icon: Groups,
    path: `${PAGE_URL.performance}${PAGE_URL.teammates}`,
    element: <PeersViewComponent />,
    sideMenuView: true,
    children: [
      {
        title: "Peers View",
        icon: AccountTree,
        path: PAGE_URL.peersView,
        element: <PeersViewComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Appraisee View",
        icon: AutoGraph,
        path: PAGE_URL.appraiseeView,
        element: <AppraiseeViewComponent />,
        sideMenuView: true,
        children: [],
      },
    ],
  },
  {
    title: "Skill Set Matrix",
    icon: BatchPrediction,
    path: PAGE_URL.skill_sets,
    element: <AppraisalComponent />,
    sideMenuView: true,
    children: [],
  },
  {
    title: "Activities",
    icon: Timeline,
    path: `${PAGE_URL.performance}${PAGE_URL.activities}`,
    element: null,
    sideMenuView: true,
    children: [
      {
        title: "Review Extension",
        icon: RateReview,
        path: PAGE_URL.reviewExtension,
        element: <AppraisalComponent />,
        sideMenuView: true,
        children: [],
      },
    ],
  },
  {
    title: "Employee Salary",
    icon: Payments,
    path: PAGE_URL.employee_salary,
    element: <AppraisalComponent />,
    sideMenuView: true,
    children: [],
  },
  {
    title: "Goals",
    icon: Flag,
    path: PAGE_URL.goals,
    element: <AppraisalComponent />,
    sideMenuView: true,
    children: [],
  },
  {
    title: "Multi-rater View",
    icon: Reviews,
    path: PAGE_URL.multi_rater_view,
    element: <AppraisalComponent />,
    sideMenuView: true,
    children: [],
  },
  {
    title: "Settings",
    icon: Settings,
    path: `${PAGE_URL.performance}${PAGE_URL.settings}`,
    element: null,
    sideMenuView: true,
    children: [
      {
        title: "Appraisal Cycle",
        icon: Sync,
        path: PAGE_URL.appraisal,
        element: <AppraisalComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Appraisal Form",
        icon: Sync,
        path: `${PAGE_URL.appraisal}${PAGE_URL.add_appraisal}`,
        element: <AppraisalFormComponent />,
        sideMenuView: false,
        children: [],
      },
      {
        title: "Performance Modules",
        icon: ViewModule,
        path: PAGE_URL.performance_modules,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Continuous Review",
        icon: Grading,
        path: PAGE_URL.continuous_review,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Notifications",
        icon: Notifications,
        path: PAGE_URL.notifications,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Feedback",
        icon: Comment,
        path: PAGE_URL.feedback,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Skill Sets",
        icon: TipsAndUpdates,
        path: PAGE_URL.skill_sets,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "KRA",
        icon: Speed,
        path: PAGE_URL.kra,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Competency",
        icon: Psychology,
        path: PAGE_URL.competency,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Review Questions",
        icon: RateReview,
        path: PAGE_URL.review_questions,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Potential",
        icon: PsychologyAlt,
        path: PAGE_URL.competency,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Summary",
        icon: Summarize,
        path: PAGE_URL.summary,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Performance Administrator",
        icon: ManageAccounts,
        path: PAGE_URL.performance_administrator,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "Goals Settings",
        icon: SportsScore,
        path: PAGE_URL.goals_settings,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
      {
        title: "General Settings",
        icon: Settings,
        path: PAGE_URL.general_settings,
        element: <PerformanceModulesComponent />,
        sideMenuView: true,
        children: [],
      },
    ],
  },
]
